scara_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - scara_J1
    - scara_J2
    - scara_J3
    - scara_J4
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    scara_J1: {trajectory: 0.1, goal: 0.1}
    scara_J2: {trajectory: 0.1, goal: 0.1}
    scara_J3: {trajectory: 0.1, goal: 0.1}
    scara_J4: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10
  gains:
    scara_J1: {p: 100.0, i: 0.01, d: 10.0}
    scara_J2: {p: 100.0, i: 0.01, d: 10.0}
    scara_J3: {p: 100.0, i: 0.01, d: 10.0}
    scara_J4: {p: 100.0, i: 0.01, d: 10.0}
  

handler_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - handler_J1
    - handler_J2
    - handler_J3
    - handler_J4
    - handler_J5
    - handler_J6
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    handler_J1: {trajectory: 0.1, goal: 0.1}
    handler_J2: {trajectory: 0.1, goal: 0.1}
    handler_J3: {trajectory: 0.1, goal: 0.1}
    handler_J4: {trajectory: 0.1, goal: 0.1}
    handler_J5: {trajectory: 0.1, goal: 0.1}
    handler_J6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10
  gains:
    handler_J1: {p: 100.0, i: 0.01, d: 10.0}
    handler_J2: {p: 100.0, i: 0.01, d: 10.0}
    handler_J3: {p: 100.0, i: 0.01, d: 10.0}
    handler_J4: {p: 100.0, i: 0.01, d: 10.0}
    handler_J5: {p: 100.0, i: 0.01, d: 10.0}
    handler_J6: {p: 100.0, i: 0.01, d: 10.0}


polisher_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - polisher_J1
    - polisher_J2
    - polisher_J3
    - polisher_J4
    - polisher_J5
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    polisher_J1: {trajectory: 0.1, goal: 0.1}
    polisher_J2: {trajectory: 0.1, goal: 0.1}
    polisher_J3: {trajectory: 0.1, goal: 0.1}
    polisher_J4: {trajectory: 0.1, goal: 0.1}
    polisher_J5: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10
  gains:
    polisher_J1: {p: 100.0, i: 0.01, d: 10.0}
    polisher_J2: {p: 100.0, i: 0.01, d: 10.0}
    polisher_J3: {p: 100.0, i: 0.01, d: 10.0}
    polisher_J4: {p: 100.0, i: 0.01, d: 10.0}
    polisher_J5: {p: 100.0, i: 0.01, d: 10.0}